apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: admin
spec:
  profile:
    displayName: Admin
    email: admin@admin.com	
    picture: https://avatars.githubusercontent.com/joaosilva
  memberOf: [admin]
