apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: u-admin
spec:
  profile:
    displayName: Usuário Admin
    email: 	admin@admin.com
    picture: https://avatars.githubusercontent.com/joaosilva
  memberOf: [admin]
